services:
  ui:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: codebot-app
    container_name: codebot-ui
    command: python -m streamlit run src/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../docs:/app/docs
      - ../.env:/app/.env
      - ../cloned_repos:/app/cloned_repos
      - ../uploaded_repos:/app/uploaded_repos
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  webhook:
    image: codebot-app
    depends_on:
      - ui
    container_name: codebot-webhook
    command: python src/webhook_server.py
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../docs:/app/docs
      - ../.env:/app/.env
      - ../cloned_repos:/app/cloned_repos
      - ../uploaded_repos:/app/uploaded_repos
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  data:
  docs:
